package com.github.sleepypanda.feesh.settings.models

import com.github.sleepypanda.feesh.constants.SeaCreatureNames

// IDs should be aligned with Sea Creatures names using the following logic:
// displayName = Carrot King -> CARROT_KING
enum class HpTrackableSeaCreatureTypes(val displayName: String, val isEnabledByDefault: Boolean) {
    ABYSSAL_MINER(SeaCreatureNames.ABYSSAL_MINER, true),
    AGARIMOO(SeaCreatureNames.AGARIMOO, false),
    ALLIGATOR(SeaCreatureNames.ALLIGATOR, true),
    ATOLL_CROAKER(SeaCreatureNames.ATOLL_CROAKER, false),
    BANSHEE(SeaCreatureNames.BANSHEE, false),
    BAYOU_SLUDGE(SeaCreatureNames.BAYOU_SLUDGE, false),
    BLUE_RINGED_OCTOPUS(SeaCreatureNames.BLUE_RINGED_OCTOPUS, true),
    BLUE_SHARK(SeaCreatureNames.BLUE_SHARK, false),
    BLOATED_MITHRIL_GRUBBER(SeaCreatureNames.BLOATED_MITHRIL_GRUBBER, true),
    BOGGED(SeaCreatureNames.BOGGED, false),
    CARROT_KING(SeaCreatureNames.CARROT_KING, true),
    CATFISH(SeaCreatureNames.CATFISH, false),
    DEEP_SEA_PROTECTOR(SeaCreatureNames.DEEP_SEA_PROTECTOR, false),
    DROWNED_CAPTAIN(SeaCreatureNames.DROWNED_CAPTAIN, false),
    DUMPSTER_DIVER(SeaCreatureNames.DUMPSTER_DIVER, false),
    ENT(SeaCreatureNames.ENT, false),
    FIERY_SCUTTLER(SeaCreatureNames.FIERY_SCUTTLER, true),
    FIRE_EEL(SeaCreatureNames.FIRE_EEL, false),
    FIREPROOF_WITCH(SeaCreatureNames.FIREPROOF_WITCH, false),
    FLAMING_WORM(SeaCreatureNames.FLAMING_WORM, false),
    FLIPFLOPPER("Flipflopper", true),
    FROG_MAN(SeaCreatureNames.FROG_MAN, false),
    FROG_PRINCE(SeaCreatureNames.FROG_PRINCE, true),
    FROZEN_STEVE(SeaCreatureNames.FROZEN_STEVE, false),
    FROSTY(SeaCreatureNames.FROSTY, false),
    GORF(SeaCreatureNames.GORF, false),
    GREAT_WHITE_SHARK(SeaCreatureNames.GREAT_WHITE_SHARK, true),
    GRIM_REAPER(SeaCreatureNames.GRIM_REAPER, true),
    GRINCH(SeaCreatureNames.GRINCH, false),
    GUARDIAN_DEFENDER(SeaCreatureNames.GUARDIAN_DEFENDER, false),
    INKLING(SeaCreatureNames.INKLING, false),
    JAWBUS_FOLLOWER("Jawbus Follower", true),
    JUMPIN_JACK(SeaCreatureNames.JUMPIN_JACK, false),
    LARGE_MITHRIL_GRUBBER(SeaCreatureNames.LARGE_MITHRIL_GRUBBER, false),
    LAVA_BLAZE(SeaCreatureNames.LAVA_BLAZE, false),
    LAVA_FLAME(SeaCreatureNames.LAVA_FLAME, false),
    LAVA_LEECH(SeaCreatureNames.LAVA_LEECH, false),
    LAVA_PIGMAN(SeaCreatureNames.LAVA_PIGMAN, false),
    LORD_JAWBUS(SeaCreatureNames.LORD_JAWBUS, true),
    LOTUS_GUARDIAN(SeaCreatureNames.LOTUS_GUARDIAN, false),
    MAGMA_PILLAR(SeaCreatureNames.MAGMA_PILLAR, false),
    MAGMA_SLUG(SeaCreatureNames.MAGMA_SLUG, false),
    MANTA_RAY(SeaCreatureNames.MANTA_RAY, false),
    MEDIUM_MITHRIL_GRUBBER(SeaCreatureNames.MEDIUM_MITHRIL_GRUBBER, false),
    MOOGMA(SeaCreatureNames.MOOGMA, false),
    NESSIE(SeaCreatureNames.NESSIE, true),
    NIGHTMARE(SeaCreatureNames.NIGHTMARE, false),
    NURSE_SHARK(SeaCreatureNames.NURSE_SHARK, false),
    NUTCRACKER(SeaCreatureNames.NUTCRACKER, true),
    OASIS_RABBIT(SeaCreatureNames.OASIS_RABBIT, false),
    OASIS_SHEEP(SeaCreatureNames.OASIS_SHEEP, false),
    PHANTOM_FISHER(SeaCreatureNames.PHANTOM_FISHER, true),
    PLHLEGBLAST(SeaCreatureNames.PLHLEGBLAST, true),
    POISONED_WATER_WORM(SeaCreatureNames.POISONED_WATER_WORM, false),
    PUDDLE_JUMPER(SeaCreatureNames.PUDDLE_JUMPER, true),
    PYROCLASTIC_WORM(SeaCreatureNames.PYROCLASTIC_WORM, false),
    RAGNAROK(SeaCreatureNames.RAGNAROK, true),
    REINDRAKE(SeaCreatureNames.REINDRAKE, true),
    RIDER_OF_THE_DEEP(SeaCreatureNames.RIDER_OF_THE_DEEP, false),
    SCARECROW(SeaCreatureNames.SCARECROW, false),
    SEA_ARCHER(SeaCreatureNames.SEA_ARCHER, false),
    SEA_LEECH(SeaCreatureNames.SEA_LEECH, false),
    SEASHINE("Seashine", true),
    SEA_WALKER(SeaCreatureNames.SEA_WALKER, false),
    SEA_WITCH(SeaCreatureNames.SEA_WITCH, false),
    SMALL_MITHRIL_GRUBBER(SeaCreatureNames.SMALL_MITHRIL_GRUBBER, false),
    SNAPPING_TURTLE(SeaCreatureNames.SNAPPING_TURTLE, false),
    SQUID(SeaCreatureNames.SQUID, false),
    STRIDERSURFER(SeaCreatureNames.STRIDERSURFER, false),
    TADGANG(SeaCreatureNames.TADGANG, false),
    TAURUS(SeaCreatureNames.TAURUS, false),
    THE_LOCH_EMPEROR(SeaCreatureNames.THE_LOCH_EMPEROR, true),
    THUNDER(SeaCreatureNames.THUNDER, true),
    TIGER_SHARK(SeaCreatureNames.TIGER_SHARK, false),
    TITANOBOA(SeaCreatureNames.TITANOBOA, true),
    TRASH_GOBBLER(SeaCreatureNames.TRASH_GOBBLER, false),
    VANQUISHER(SeaCreatureNames.VANQUISHER, true),
    VOLCANIC_SNAIL(SeaCreatureNames.VOLCANIC_SNAIL, false),
    WATER_HYDRA(SeaCreatureNames.WATER_HYDRA, true),
    WATER_WORM(SeaCreatureNames.WATER_WORM, false),
    WEREWOLF(SeaCreatureNames.WEREWOLF, false),
    WETWING(SeaCreatureNames.WETWING, false),
    WIKI_TIKI(SeaCreatureNames.WIKI_TIKI, true),
    WIKI_TIKI_LASER_TOTEM("Wiki Tiki Laser Totem", true),
    YETI(SeaCreatureNames.YETI, true);

    override fun toString(): String = displayName // Show display name in UI, but internally it uses name
}
